### ISSUE TITLE
draft ui for filter result

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/tiled-viz2023#12]

**Comment by olliviergassant** [comment]
The ui for filter results has been update and added to the "ui_files" as the name "filter_window_version2.ui", Can I close this issue?

**Comment by prjemian** [comment]
This is still in a [branch](https://github.com/BCDA-APS/tiled-viz2023/tree/12-result-ui)?  We should make a pull request for that branch (and set the "PR" so that it automatically closes this issue once the PR is merged).  Before merging, we'll review using GitHub's tools for that process.

**Comment by prjemian** [comment]
You can close this, that branch is for for #13.
