### ISSUE TITLE
Create a storyboard of the desired GUI

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/tiled-viz2023#2]
Create a simple sketch of what we think the GUI should look like.

One reference is the dview software, for visualizing MDA file data.  PyMCA & NeXpy are other examples but add additional complexity.

**Comment by prjemian** [comment]
https://www.figma.com/ is a good place to build a storyboard in a collaborative session

**Comment by rodolakis** [comment]
What dview looks like:


![image](https://github.com/BCDA-APS/tiled-viz2023/assets/39918069/149f15de-4f4b-4089-8330-499573d0f9b5)

**Comment by prjemian** [comment]
From the USAXS GUI (in IgorPro):
![image](https://github.com/BCDA-APS/tiled-viz2023/assets/2279984/92613ae9-ad2f-49f4-b5f2-e66e79ff4a24)

![image](https://github.com/BCDA-APS/tiled-viz2023/assets/2279984/51a955d0-f16a-4828-a19d-c8c2c229d6c9)

**Comment by prjemian** [comment]
Words of advice: Do NOT show the UUID to the user unless they really, really want it.

**Comment by rodolakis** [comment]
<img width="800" alt="image" src="https://github.com/BCDA-APS/tiled-viz2023/assets/39918069/15ff1fc7-b6e9-408c-94ca-ca6d4490f994">

**Comment by olliviergassant** [comment]
Initial Storyboard Design without suggested changes:

https://anl.box.com/s/2ffyi8watf4h2vzztw7id81cajnubj24

**Comment by prjemian** [comment]
Also consider that the number of search/filter terms is not limited to just the terms shown.  More could be added.

**Comment by rodolakis** [comment]
PyMca:

<img width="1781" alt="image" src="https://github.com/BCDA-APS/tiled-viz2023/assets/39918069/461ff86a-75ed-4b2a-8c45-ae4d87f23f95">

**Comment by rodolakis** [comment]
PyMca for 2D data:

<img width="1789" alt="image" src="https://github.com/BCDA-APS/tiled-viz2023/assets/39918069/376111a4-f611-41f2-9fbc-6118f97e1437">

**Comment by rodolakis** [comment]
PyMca is by far the most used GUI, would be a good goal to reproduce some of its basic features.

**Comment by prjemian** [comment]
This view of an area detector image is from NeXpy:

![image](https://github.com/BCDA-APS/tiled-viz2023/assets/2279984/bea70b17-968e-466f-9816-11433387f10e)

**Comment by prjemian** [comment]
Since the [proposed storyboard is behind a credentialed wall](https://github.com/BCDA-APS/tiled-viz2023/issues/2#issuecomment-1579243852), I'll copy those views here.

**Comment by prjemian** [comment]
![Slide1](https://github.com/BCDA-APS/tiled-viz2023/assets/2279984/b24c3ccd-6952-4c34-b745-82a2d73f6911)
![Slide2](https://github.com/BCDA-APS/tiled-viz2023/assets/2279984/aa91c974-0d28-4322-9264-ebd679e362dd)
![Slide3](https://github.com/BCDA-APS/tiled-viz2023/assets/2279984/f4130d3e-a04b-4e7c-a94b-279d68fc5b76)
![Slide4](https://github.com/BCDA-APS/tiled-viz2023/assets/2279984/064b84d1-0e47-47e6-af93-cd9c5d63a7b6)
![Slide5](https://github.com/BCDA-APS/tiled-viz2023/assets/2279984/3cbaeb70-1b11-40e0-a77c-4dfb40a3bc38)
![Slide6](https://github.com/BCDA-APS/tiled-viz2023/assets/2279984/f76986e3-8cf9-4544-bf7f-654569453cea)
![Slide7](https://github.com/BCDA-APS/tiled-viz2023/assets/2279984/79c6efb3-ef29-46c0-b26f-4ca3455aa321)
