### ISSUE TITLE
look at the tiled client UI

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/tiled-viz2023#3]
Try the UI client provided by tiled server.  It's capable of a lot, it shows many features of the tiled server, but the human interface features are extremely limited.  We can develop a list of improvements.

**Comment by prjemian** [comment]
Can this issue be closed?

**Comment by olliviergassant** [comment]
Yes, I will close the issue.

**Comment by olliviergassant** [comment]
Yes, I will close the issue.
