### ISSUE TITLE
improve tableview

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/tiled-viz2023#43]
- remove quotation and brackets from detector
- make scan_id text centered
- adjust column size
- add positionner to table content

**Comment by prjemian** [comment]
It's time to make a PR for branch [43-improve-tableview](https://github.com/BCDA-APS/tiled-viz2023/tree/43-improve-tableview).  In addition to this issue, this branch includes fixes for these issues:

- #42
- #45
- #46
