### ISSUE TITLE
Visualize metadata when run is selected

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/tiled-viz2023#58]
When a run is selected in the `resultswindow`, display a representation of its metadata in a tab of the visualization panel.

Needs a `visualizationpanel` ui/py pair of files.  The panel needs to have tabs, at least for `plot`, `data`, and `metadata`.

**Comment by olliviergassant** [comment]
Viz panel was created along side .py
Metadata was show within the viz panel in YAML format 
Run is selected through doubleClick() method

**Comment by prjemian** [comment]
Example:

![image](https://github.com/BCDA-APS/tiled-viz2023/assets/2279984/fc533a63-1fe4-45cf-9185-0f5d460f4b94)
